### ISSUE TITLE
/www/jekyll_patternbot

### ISSUE THREAD

**Issue by sander-aaron** [sander-aaron/portfolio#1]
@thomasjbradley
<img width="572" alt="Screen Shot 2019-10-01 at 5 40 29 PM" src="https://user-images.githubusercontent.com/31959117/66002958-df950200-e472-11e9-8a0c-ad23b6172c80.png">
Here is a screenshot of my terminal where I'm getting "The path `/www/jekyll_patternbot` does not exist."
I was trying to run bundle init and bundle install and bundle exec jekyll serve

**Comment by thomasjbradley** [comment]
On this line of code:
https://github.com/sander-aaron/portfolio/blob/master/Gemfile#L10

Remove this code:
```rb
, :path => '/www/jekyll_patternbot/'
```

**Comment by thomasjbradley** [comment]
Where did you get that chunk of code anyways?

**Comment by sander-aaron** [comment]
I never put it in, I guess the file came with it. But thank you, I will test it when I'm out of class

**Comment by thomasjbradley** [comment]
Oh—I committed it into the original repository! It’s fixed now.

**Comment by sander-aaron** [comment]
So I should just have to pull down and I'll be able to set up my pattern library?

**Comment by thomasjbradley** [comment]
Nope. Delete some of the code like I suggested a few comments above.

**Comment by sander-aaron** [comment]
Yeh, I fixed it. I have my pattern library up and running and have a few patterns added in now! Just need to make them look good
