### ISSUE TITLE
Peer Critique

### ISSUE THREAD

**Issue by migr0001** [sander-aaron/portfolio#2]
Great pattern library so far! I've made a few notes:
- I loved the consistency of the two contrasting colours (yellow and blue) and the shapes used.
- I also love the logo!
- In the Navigation (the main header), the logo and the links overlap in smaller screen sizes.
<img width="307" alt="Screen Shot 2019-10-16 at 1 41 56 PM" src="https://user-images.githubusercontent.com/31969141/66944655-9a98d000-f01b-11e9-99ae-8e6864fcaa50.png">
- Not sure if this is a personal style where you have the image at the bottom in medium screen widths, but if you wanted the image horizontally centered in all screen widths, you can add a class of .unit-content-center-vertical 
<img width="615" alt="Screen Shot 2019-10-16 at 1 43 12 PM" src="https://user-images.githubusercontent.com/31969141/66945095-725da100-f01c-11e9-9568-f92a7ccedf67.png">

Overall, great pattern library!

**Comment by sander-aaron** [comment]
Thank you for the feedback! I have to fix that nav!
