### ISSUE TITLE
How to make patterns actually work?

### ISSUE THREAD

**Issue by sander-aaron** [sander-aaron/portfolio#5]
Hey @thomasjbradley
I'm trying to create my home page and I'm running into an issue of how to tell my pattern library to place in my previews. 
This is what I have so far:
<img width="436" alt="Screen Shot 2019-10-17 at 8 31 41 PM" src="https://user-images.githubusercontent.com/31959117/67057151-5beb3e80-f11d-11e9-8e05-044f32d0e036.png">
And this is what is showing up in chrome:
<img width="1280" alt="Screen Shot 2019-10-17 at 8 32 14 PM" src="https://user-images.githubusercontent.com/31959117/67057161-6574a680-f11d-11e9-8b0b-768be8090d57.png">
As you can see, nothing from the md files is being inputted but the html is. I'm not sure how to tell the patterns which md is supposed to go where.

Thanks

**Comment by thomasjbradley** [comment]
Similar to how we did it somewhere else on your website:

1. Create a variable: `{% assign . . . %}`
2. User the variable in the include

**Comment by sander-aaron** [comment]
Ah! Ok thank you!

**Comment by sander-aaron** [comment]
So I got the patterns working and have the majority of my website built but I am trying to add my moreworks.html page that just has some other things that I have done. When I go to see the page (http://localhost:4000/morework.html) it comes back with a "Not Found" message.

How can I go about setting up the page so that it works?

**Comment by thomasjbradley** [comment]
Get rid of `.html` and see if that works.

**Comment by sander-aaron** [comment]
:O Thank you for all your help!
